id: atlas-anndata-bundle
description: "A full decription of an annData file presented as a candidate for bundling and ingestion into Single-cell Expression Atlas."
properties:
    exp-name: 
        type: string
    droplet:
        type: boolean
    matrices:
        type: array

required:
  - exp-name
  - droplet
