# Top-level parameters

exp-name: E-MTAB-1234
droplet: False

# Matrices, slots correspond to keys in .layers, unless .X or .raw.X, which
# which case those are interpreted as explicit top-level slots in the anndata.

matrices:
  - type: counts
    entries: 
      - slot: raw.X
      - slot: filtered
        parameters:
            min_count: 3
      - slot: filtered_normalised

# Cell groups, slots correspond to columns in .obs. Two categories:
#     - curated: present before analysis. These will be output for curation.
#     - analysis: derived from analysis: e.g. clusters.  
# 
# Cell groupings marked with 'markers: True' will have those markers written to
# the bundle

cell_groups:
  - type: curation
    entries:
      - slot: organism
  - type: analysis
    entries:
      - slot: louvain_resolution_0.7
        parameters:
          alorithm: louvain
          resolution: 0.7
          markers: True
      - slot: louvain_resolution_1.0
        parameters:
          alorithm: louvain
          resolution: 1.0
          markers: True

# Dimension reductions, slots correspond to keys in .obsm

dimension_reductions:
  - type: umap
    entries: 
     - slot: X_umap_neighbors_n_neighbors_3
       parameters:
          n_neighbors: 3
     - slot: X_umap_neighbors_n_neighbors_10
       parameters:
         n_neighbors: 5
     - slot: X_umap_neighbors_n_neighbors_10
       parameters:
         n_neighbors: 10
