id: atlas-anndata-bundle
description: "A full decription of an annData file presented as a candidate for bundling and ingestion into Single-cell Expression Atlas."
properties:
    exp-name: 
        type: string
    droplet:
        type: boolean
    matrices:
        type: object
        properties:
            load_to_scxa_db:
                type: string
            entries:
                type: array 
                items:
                    type: object
                    properties:
                        slot:
                            type: string
                        name:
                            type: string
                        measure: 
                            type: string
                        gene_filtered: 
                            type: boolean
                        cell_filtered: 
                            type: boolean
                        normalised: 
                            type: boolean
                        log_transformed: 
                            type: boolean
                        scaled: 
                            type: boolean
                        parameters:
                            type: object
                    required: [ name, measure, gene_filtered, normalised, log_transformed ]
                    additionalProperties: False
    gene_meta:
        type: object
        properties:
            name_field:
                type: string
        required: [ name_field ]

    cell_meta:
        type: object
        properties:
            entries:
                type: array
                items:
                    type: object
                    properties:
                        slot:
                            type: string
                        default:
                            type: boolean
                        kind: 
                            type: string
                            pattern: "^(curation|analysis|clustering)$"
                        markers:
                            type: boolean
                        parameters:
                            type: object
                    required: [ slot, kind, markers ]

    dimension_reductions:
        type: object
        properties:
            entries:
                type: array
                items:
                    type: object
                    properties:
                        slot:
                            type: string
                        default:
                            type: boolean
                        kind: 
                            type: string
                            pattern: "^(tsne|umap|pca)$"
                        parameters:
                            type: object
                    required: [ slot, kind ]

    software_versions:
        type: array
        items:
            type: object
            properties:
                analysis:
                    type: string
                software:
                    type: string
                version:
                    type: string
            required: [ analysis, software, version ]

required:
  - matrices
  - exp-name
  - droplet
