name: Python package

on: [push, pull_request]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: '--check --verbose --include="\.pyi?$|bin/*" .'
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint .py files
        uses: py-actions/flake8@v2
        with:
          path: "."
          args: '-vv'
      - name: flake8 Lint scripts
        uses: py-actions/flake8@v2
        with:
          path: "bin"
          args: '--filename="*" -vv'
      - name: Install dependencies
        run: |
          pip install .
      - name: Run function tests
        run: |
          python atlas_anndata/funcs.py
      - name: Test CLI: config creation from annData
        run: |
          make_starting_config_from_anndata atlas_anndata/data/E-MTAB-6077.project.h5ad test_config_from_anndata.yaml --atlas-style --exp-name E-MTAB=1234 --droplet
      - name: Test CLI: Validate annData against schema and config
        run: |
          validate_anndata_with_config test_config_from_anndata.yaml atlas_anndata/data/E-MTAB-6077.project.h5ad
